alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  persistentVolume:
    enabled: false #Nao configurei persistent volume pois eh apenas lab
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.felipeavila.com.br
