
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build-and-push-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/desafio-app:${{ github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-app-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push manifests to desafio-apps apps-repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: manifests
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: desafio-apps
          target-directory: desafio-app
          user-email: devops@felipe.avila
          user-name: devops
